api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Person/Entity'
            - '%kernel.project_dir%/src/Person/Controller'
            - '%kernel.project_dir%/src/Person/ApiResource'
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
