api_platform:
    title: 'Hello API Platform'
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary:
                - Content-Type
                - Authorization
                - Origin
    mapping:
        paths:
            - '%kernel.project_dir%/src/Shared/Entity'
            - '%kernel.project_dir%/src/Shared/Controller'
            - '%kernel.project_dir%/src/Shared/ApiResource'
            - '%kernel.project_dir%/src/User/Entity'
            - '%kernel.project_dir%/src/User/Controller'
            - '%kernel.project_dir%/src/User/ApiResource'
