doctrine:
    orm:
        mappings:
            Shared:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared'
                prefix: App\Shared\Entity
                alias: Shared
